# Generated by Django 6.1.1 on 2026-09-29 10:42

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parcels', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Parcel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('weight', models.DecimalField(decimal_places=3, max_digits=10)),
                ('content_cost_usd', models.DecimalField(decimal_places=2, max_digits=12)),
                ('delivery_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('delivery_cost_calculated_at', models.DateTimeField(blank=True, null=True)),
                ('session_key', models.CharField(db_index=True, max_length=64)),
                ('company_id', models.BigIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='parcels', to='parcels.parceltype')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
