# Generated by Django 6.1.1 on 2026-09-29 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parcels', '0002_parcel'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='parcel',
            index=models.Index(fields=['session_key'], name='parcel_session_idx'),
        ),
        migrations.AddIndex(
            model_name='parcel',
            index=models.Index(fields=['type'], name='parcel_type_idx'),
        ),
        migrations.AddIndex(
            model_name='parcel',
            index=models.Index(fields=['company_id'], name='parcel_company_idx'),
        ),
        migrations.AddIndex(
            model_name='parcel',
            index=models.Index(condition=models.Q(('delivery_cost__isnull', True)), fields=['id'], name='parcel_no_cost_idx'),
        ),
    ]
