# Generated by Django 6.1.1 on 2026-09-29 12:02

from django.db import migrations
from django.db.backends.base.schema import BaseDatabaseSchemaEditor
from django.db.migrations.state import StateApps


def create_types(apps: StateApps, schema_editor: BaseDatabaseSchemaEditor) -> None:
    """Создаёт начальные типы посылок."""

    ParcelType = apps.get_model("parcels", "ParcelType")
    ParcelType.objects.get_or_create(code="clothes", defaults={"name": "одежда"})
    ParcelType.objects.get_or_create(code="electronics", defaults={"name": "электроника"})
    ParcelType.objects.get_or_create(code="misc", defaults={"name": "разное"})


def delete_types(apps: StateApps, schema_editor: BaseDatabaseSchemaEditor) -> None:
    """Удаляет начальные типы при откате."""
    
    ParcelType = apps.get_model("parcels", "ParcelType")
    ParcelType.objects.filter(code__in=["clothes", "electronics", "misc"]).delete()


class Migration(migrations.Migration):

    dependencies = [
        ("parcels", "0003_parcel_parcel_session_idx_parcel_parcel_type_idx_and_more"),
    ]

    operations = [
        migrations.RunPython(create_types, delete_types),
    ]
